### ISSUE TITLE
The link http://provocare.fr/ doesn't work

### ISSUE THREAD

**Issue by caroliner** [Asche42/provocare#6]
I don't know why but this link doesn't work. The link www.provocare.fr works.

**Comment by thomascharbonnel** [comment]
Most likely only a configuration problem on our domain name provider.

**Comment by caroliner** [comment]
ok no problem.

**Comment by thomascharbonnel** [comment]
Heroku uses dynamic IPs. The heroku domain name (provocare.herokuapp.com) can't be used as domain name root CNAME. Can't be solved without paying, I won't.

**Comment by caroliner** [comment]
How much is it ?

**Comment by thomascharbonnel** [comment]
Depends on the solution. From what I've seen, around $5/month. Might have found a free alternative. Anyway, it's not high up my priority stack.
